[package]
name = "enc"
version = "0.1.0"
edition = "2021"

[lib]
name = "enc"
path = "src/lib.rs"

[dependencies]
zenc-sys = { path = "../zenc-sys" }
arrow2 = { version = "0.18.0", features = ["compute"] }
bytemuck = { version = "1", features = ["derive"] }
dyn-clone = "1.0.16"
roaring = "0.10.2"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25.3"
